# -*- coding: utf-8 -*-
"""Coffee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hvJLJPQiS13Ap903CqLyDK_cGn9s2A-
"""

import datetime

def caffeine_audit():
    print("--- 🕵️‍♂️ THE LASS DOSSIER: CAFFEINE CASE ---")

    #Data from user
    try:
        cups_drunk = int(input("Cups of black coffee consumed today: "))
        hours_to_dawn = int(input("Hours remaining until dawn: "))
    except ValueError:
        print("❗Error: Gremlins only understand integers. Try again.")
        return

    #Unique Status
    is_coffee_gremlin = True

    #Logic: 1 cup of coffee ensures approximetly 2 hours of focus
    energy_reserve = cups_drunk * 2

    print("\n--- 🔍 INVESTIGATION RESULTS ---")
    if energy_reserve >= hours_to_dawn:
        print(f"✔️Status: SAFE. You have {energy_reserve} hours of fuel.")
        print("☕ Quote: 'I’m still standing, ready for more.'")
    else:
        deficit = hours_to_dawn - energy_reserve
        print(f"❗WARNING: CRITICAL DEFICIT. You need {deficit // 2 + 1} more cups.")
        print("Observation: 'I am but a silhouette of what I used to be...'")

    print("\n--- CASE CLOSED: ONLY THE REMAINS OF THE MUG LEFT ---")

if __name__ == "__main__":
    caffeine_audit()